[package]
name = "jason/wally"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
Rodux = "roblox/rodux@3.0.0"
RoactRodux = "roblox/roact-rodux@0.3.0"
Hooks = "kampfkarren/roact-hooks@0.5.0"
RoactSpring = "chriscerie/roact-spring@1.0.1"

Promise = "evaera/promise@4.0.0"
Knit = "sleitnick/knit@1.4.7"